<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="TestFlowTwoCancel" duration-ms="29559" started-at="2023-08-21T07:12:52Z" finished-at="2023-08-21T07:13:22Z">
    <groups>
    </groups>
    <test name="Command line test" duration-ms="29559" started-at="2023-08-21T07:12:52Z" finished-at="2023-08-21T07:13:22Z">
      <class name="TestFlowTwoCancel">
        <test-method status="PASS" signature="setUp()[pri:0, instance:TestFlowTwoCancel@5315b42e]" name="setUp" is-config="true" duration-ms="1155" started-at="2023-08-21T15:12:52Z" finished-at="2023-08-21T15:12:53Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:TestFlowTwoCancel@5315b42e]" name="testLogin" duration-ms="6889" started-at="2023-08-21T15:12:53Z" finished-at="2023-08-21T15:13:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="PASS" signature="testViewOrders()[pri:0, instance:TestFlowTwoCancel@5315b42e]" name="testViewOrders" duration-ms="3503" started-at="2023-08-21T15:13:00Z" depends-on-methods="TestFlowTwoCancel.testLogin" finished-at="2023-08-21T15:13:04Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testViewOrders -->
        <test-method status="FAIL" signature="testClickOrderCancel()[pri:0, instance:TestFlowTwoCancel@5315b42e]" name="testClickOrderCancel" duration-ms="17926" started-at="2023-08-21T15:13:04Z" depends-on-methods="TestFlowTwoCancel.testViewOrders" finished-at="2023-08-21T15:13:22Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertEqualsImpl(Assert.java:134)
	at org.testng.Assert.assertEquals(Assert.java:115)
	at org.testng.Assert.assertEquals(Assert.java:304)
	at org.testng.Assert.assertEquals(Assert.java:314)
	at TestFlowTwoCancel.testClickOrderCancel(TestFlowTwoCancel.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:77)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:110)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:106)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testClickOrderCancel -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:TestFlowTwoCancel@5315b42e]" name="tearDown" is-config="true" duration-ms="71" started-at="2023-08-21T15:13:22Z" finished-at="2023-08-21T15:13:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- TestFlowTwoCancel -->
    </test> <!-- Command line test -->
  </suite> <!-- TestFlowTwoCancel -->
</testng-results>
